In [2]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer 
import numpy as np
from textblob import TextBlob

In [3]:
df= pd.read_csv('data/trs_train.tsv', sep='\t')
X_train = (df['sentence'])
y_train = df['label']
df_test = pd.read_csv('data/trs_dev.tsv', sep='\t')
X_test = df_test['sentence']
y_test = df_test['label']

In [49]:
from textblob import TextBlob
from textblob import Word


def replace_with_not(X, A):
    w_nt = "n't"
    w_not = "not"
    p = 0
    print('progress: ', end='')
    for i in range(len(X)):
        sent = X_train.loc[i]
        sent = sent.replace(w_nt, w_not)
        X_train.loc[i] = lemmatize(sent, A)
        if p%500 == 0:
            print('#', end='')
        p += 1

def lemmatize(s, A):
    sentence = TextBlob(s)
#     print(f'len: {len(sentence.words)}, words: {sentence.words}')
    words = []
    for i in range(len(sentence.words)):
        words.append(Word(sentence.words[i].lemmatize()))
    A.append(len(words))
    return " ".join(words)
    
    
tr_len = []
tt_len = []
print('Transform Train:')
replace_with_not(X_train, tr_len)
print(f'train len: {tr_len}')

print('Transform Test:')
replace_with_not(X_test, tt_len)
print(f'test len: {tt_len}')

print('Done.')

Transform Train:
progress: ########################################

KeyboardInterrupt: 

In [0]:
dimensions = 300
# # Get embeddings from fast text file
pretrained_vectors = {}
f = open('wiki-news-300d-1M.vec', encoding="utf8")
for line in f:
    values = line.rstrip().rsplit(' ', dimensions)
    word = values[0]
    probabilities = np.asarray(values[1:], dtype='float32')
    pretrained_vectors[word] = probabilities
f.close()

In [0]:
print(pretrained_vectors['movie'])
# print(pretrained_vectors[''])

[-3.640e-02  1.014e-01 -7.890e-02 -8.490e-02 -4.530e-02 -3.090e-02
  9.820e-02  5.180e-02 -2.120e-02  1.377e-01  9.450e-02 -6.990e-02
 -6.100e-02 -6.440e-02  9.630e-02  1.563e-01 -1.418e-01 -3.340e-02
  9.620e-02  3.670e-02 -2.901e-01  1.070e-02 -1.039e-01  5.210e-02
  3.760e-02 -9.350e-02  1.076e-01  1.002e-01 -4.250e-02  4.830e-02
  1.926e-01 -1.000e-03  7.610e-02  6.600e-02  3.150e-02  1.808e-01
 -8.100e-02 -6.000e-02  1.870e-02 -6.240e-02  8.000e-04  1.161e-01
 -3.350e-02 -2.510e-02  6.240e-02  3.260e-02 -3.490e-02 -8.330e-02
  1.470e-02 -1.384e-01  2.293e-01 -1.290e-02 -6.591e-01  1.712e-01
 -5.610e-02  1.558e-01 -8.000e-02  9.910e-02 -1.858e-01 -8.670e-02
  1.081e-01  1.200e-02  2.130e-02  5.000e-02  4.600e-02  4.140e-02
 -5.770e-02  1.147e-01 -5.440e-02 -2.680e-02  9.800e-03  5.390e-02
 -8.700e-02 -6.130e-02 -2.610e-02  1.290e-02 -4.790e-02 -4.500e-02
  5.410e-02 -1.081e-01  2.600e-03 -1.019e-01 -6.060e-02 -2.171e-01
  4.550e-02  4.230e-02  1.220e-02 -1.551e-01  2.341e-01  8.940

In [0]:
from keras import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.preprocessing import sequence

from keras import layers
from keras.models import Model
from keras import initializers
from keras import layers
from keras import constraints
from keras import regularizers
from keras import optimizers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dropout
from keras.layers import Conv1D
from keras.layers import GlobalMaxPooling1D
from keras.layers import MaxPooling1D
from keras.layers import LSTM
from keras.layers import BatchNormalization
from keras.layers import Dense
from keras.layers import Embedding
from keras import optimizers

In [0]:
tknzr = Tokenizer(char_level=False, 
                  oov_token=None, 
                  num_words=None, 
                  split=' ', 
                  lower=True, 
                  filters='!"#$%&()*+,\t-./:;\n<=>?@[\]^_`{|}~ ', 
                  document_count=0)

list_x_train = list(X_train)
tknzr.fit_on_texts(list_x_train)

train_seq = tknzr.texts_to_sequences(X_train)
test_seq = tknzr.texts_to_sequences(X_test)

In [0]:
num_words = len(tknzr.word_index) + 1


In [0]:
print(num_words)

13823


In [0]:
print(max(len(sequence) for sequence in train_seq))
processing_length = int(np.percentile([len(sequence) for sequence in train_seq], 98))
print(processing_length)

49
30


In [0]:
padded_X_train = pad_sequences(train_seq, maxlen=processing_length, padding='post', value=0.0, truncating='post')
padded_X_test = pad_sequences(test_seq, maxlen=processing_length, padding='post', value=0.0, truncating='post')

In [0]:
for index, (token, token_index) in enumerate(zip(X_train[60:61], train_seq[60:61])):
    print('Comment:  {}'.format(token))
    print('Tokenized Comment: {}'.format(token_index))

Comment:  rich veins of funny stuff in this movie 
Tokenized Comment: [379, 9656, 4, 49, 409, 9, 18, 17]


In [0]:
print(padded_X_test)

[[  10    6    2 ...    0    0    0]
 [3143    3 1738 ...    0    0    0]
 [ 863   89    5 ...    0    0    0]
 ...
 [   2  295   34 ...    0    0    0]
 [   7   13  531 ...    0    0    0]
 [ 313 6556  235 ...    0    0    0]]


In [0]:
def get_embedding_matrix():
    embed_matrix = np.zeros((len(tknzr.word_index) + 1, dimensions))
    for word, index in tknzr.word_index.items():
        vector = pretrained_vectors.get(word)
        if vector is not None:
            embed_matrix[index] = vector
    return embed_matrix

embd_matrix = get_embedding_matrix()

In [0]:
index = tknzr.word_index['movie']
print(pretrained_vectors['movie']) 
print(embd_matrix[index])

[-3.640e-02  1.014e-01 -7.890e-02 -8.490e-02 -4.530e-02 -3.090e-02
  9.820e-02  5.180e-02 -2.120e-02  1.377e-01  9.450e-02 -6.990e-02
 -6.100e-02 -6.440e-02  9.630e-02  1.563e-01 -1.418e-01 -3.340e-02
  9.620e-02  3.670e-02 -2.901e-01  1.070e-02 -1.039e-01  5.210e-02
  3.760e-02 -9.350e-02  1.076e-01  1.002e-01 -4.250e-02  4.830e-02
  1.926e-01 -1.000e-03  7.610e-02  6.600e-02  3.150e-02  1.808e-01
 -8.100e-02 -6.000e-02  1.870e-02 -6.240e-02  8.000e-04  1.161e-01
 -3.350e-02 -2.510e-02  6.240e-02  3.260e-02 -3.490e-02 -8.330e-02
  1.470e-02 -1.384e-01  2.293e-01 -1.290e-02 -6.591e-01  1.712e-01
 -5.610e-02  1.558e-01 -8.000e-02  9.910e-02 -1.858e-01 -8.670e-02
  1.081e-01  1.200e-02  2.130e-02  5.000e-02  4.600e-02  4.140e-02
 -5.770e-02  1.147e-01 -5.440e-02 -2.680e-02  9.800e-03  5.390e-02
 -8.700e-02 -6.130e-02 -2.610e-02  1.290e-02 -4.790e-02 -4.500e-02
  5.410e-02 -1.081e-01  2.600e-03 -1.019e-01 -6.060e-02 -2.171e-01
  4.550e-02  4.230e-02  1.220e-02 -1.551e-01  2.341e-01  8.940

In [0]:
lstm_model = Sequential()
lstm_model.add(Embedding(len(tknzr.word_index) + 1, dimensions, weights=[embd_matrix], input_length=processing_length, trainable=True))
lstm_model.add(LSTM(60, return_sequences=True))
lstm_model.add(BatchNormalization())
lstm_model.add(MaxPooling1D(4))
lstm_model.add(GlobalMaxPooling1D())
lstm_model.add(layers.Dense(50, activation='relu'))
lstm_model.add(layers.BatchNormalization())
lstm_model.add(layers.Dropout(0.3))
lstm_model.add(layers.Dense(1, activation='sigmoid'))
lstm_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 30, 300)           4146900   
_________________________________________________________________
lstm_4 (LSTM)                (None, 30, 60)            86640     
_________________________________________________________________
batch_normalization_5 (Batch (None, 30, 60)            240       
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 7, 60)             0         
_________________________________________________________________
global_max_pooling1d_3 (Glob (None, 60)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 50)                3050      
_________________________________________________________________
batch_normalization_6 (Batch (None, 50)                200       
__________

In [0]:
# embedding_size=32
# model=Sequential()
# model.add(Embedding(num_words, embedding_size, input_length=processing_length))
# model.add(LSTM(100))
# model.add(Dense(1, activation='sigmoid'))

# print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 30, 32)            442336    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 495,637
Trainable params: 495,637
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.compile(loss='binary_crossentropy', 
             optimizer='adam', 
             metrics=['accuracy'])

In [0]:
batch_size = 64
num_epochs = 3
model.fit(padded_X_train, y_train, batch_size=batch_size, epochs=num_epochs)

Epoch 1/3
67349/67349 [==============================] - 35s 519us/step - loss: 0.0131 - acc: 0.9936
Epoch 2/3
67349/67349 [==============================] - 35s 521us/step - loss: 0.0118 - acc: 0.9937
Epoch 3/3
67349/67349 [==============================] - 35s 516us/step - loss: 0.0107 - acc: 0.9940


In [0]:
scores = model.evaluate(padded_X_test, y_test, verbose=0)
print('Test accuracy:', scores)

Test accuracy: [1.036240967862103, 0.8084862385321101]


# Naives Bayes

In [10]:
# NAIVE BAYES


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import nltk
# nltk.download('punkt')

movie_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize)
# movie_counts = movie_vec.fit_transform()
nb_train_vec = movie_vec.fit_transform(X_train)
nb_test_vec = movie_vec.transform(X_test)
print(f'shape of train vec: {nb_train_vec.shape}')
print(f'shape of test vec: {nb_test_vec.shape}')

# Convert raw frequency counts into TF-IDF values
tfidf_transformer = TfidfTransformer()
train_tfidf = tfidf_transformer.fit_transform(nb_train_vec)
test_tfidf = tfidf_transformer.transform(nb_test_vec)

print('Done.')

shape of train vec: (67349, 14296)
shape of test vec: (872, 14296)
Done.


In [16]:
import sklearn
from sklearn.naive_bayes import BernoulliNB

# Train a Multimoda Naive Bayes classifier
clf = BernoulliNB().fit(train_tfidf, y_train)

print(f'shape of train: {train_tfidf.shape}, test:{test_tfidf.shape}')
# Predicting the Test set results, find accuracy
y_pred = clf.predict(test_tfidf)
acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print(f'Accuracy for Naives Bayes: {acc}')
print('Done.')

shape of train: (67349, 14296), test:(872, 14296)
Accuracy for Naives Bayes: 0.8130733944954128
Done.


# Trying out different Features

In [6]:
t=0
for i in range(y_train.shape[0]):
    if y_train[i]==0:
        print(f'{i}: {X_train[i]}')
#         print(f'sentiment: {TextBlob(X_train[i]).sentiment}')
        t+=1
    if t==10:
        break

0: hide new secretions from the parental units
1: contains no wit , only labored gags
3: remains utterly satisfied to remain the same throughout
4: on the worst revenge-of-the-nerds clichés the filmmakers could dredge up
5: that 's far too tragic to merit such superficial treatment
8: a depressed fifteen-year-old 's suicidal poetry
10: goes to absurd lengths
11: for those moviegoers who complain that ` they do not make movies like they used to anymore
12: the part where nothing 's happening ,
13: saw how bad this movie was


In [5]:
from textblob import TextBlob

str = "no"
sentence = TextBlob(str)
print(f'len: {len(sentence.words)}, words: {sentence.words}')

len: 1, words: ['no']


for those moviegoers who complain that ` they do n't make movies like they used to anymore 
for those moviegoers who complain that ` they do not make movies like they used to anymore 
for those moviegoers who complain that ` they do n't make movies like they used to anymore 


In [58]:
import sys
# !{sys.executable} -m pip install textblob
# !{sys.executable} -m pip install jamspell
# !conda install --yes --prefix {sys.prefix} swig
# !{sys.executable} -m pip install pycontractions
# !{sys.executable} -m pip install contractions

In [56]:
from textblob import TextBlob
from pycontractions import Contractions

cont = Contractions(api_key="glove-twitter-100")
cont.load_models()

[==================================================] 100.0% 387.1/387.1MB downloaded


In [63]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/dgunda/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [8]:

sent = "contains no wit"
print(f'sentiment {sent}: {TextBlob(sent).sentiment}')
print(f'TextBlob correction {sent}: {TextBlob(sent).correct()}')

# crct_sent = list(cont.expand_texts([sent]))
# print(f'pycontra {sent}: {crct_sent}')
# print(f'TextBlob correction {sent}: {TextBlob(sent).correct()}')

# import contractions
# print(f'crct: {contractions.fix(sent)}')

# # First, you're going to need to import wordnet: 
# from nltk.corpus import wordnet 
  
# # Then, we're going to use the term "program" to find synsets like so: 
# syns = wordnet.synsets(sent) 
# print(syns[0]) 

sentiment contains no wit: Sentiment(polarity=0.0, subjectivity=0.0)
TextBlob correction contains no wit: contains no wit


shape of nb_train_vec: (67349, 14297)
hide new secretions from the parental units 
count vector: 
  (0, 5086)	1
  (0, 5900)	1
  (0, 8440)	1
  (0, 9019)	1
  (0, 10988)	1
  (0, 12670)	1
  (0, 13407)	1
tfidf vector: 
  (0, 13407)	0.4725778010918928
  (0, 12670)	0.10311924385970848
  (0, 10988)	0.49857746188436197
  (0, 9019)	0.46090177259444287
  (0, 8440)	0.2603119592841447
  (0, 5900)	0.4371688950946575
  (0, 5086)	0.21482028534700234
